spring:
  application:
    name: backend

  jackson:
    default-property-inclusion: non_null

  cloud:
    openfeign:
      oauth2:
        clientRegistrationId: twitch
        enabled: true
      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            logger-level: basic
            default-request-headers:
              Client-Id: <YOUR-CLIENT-ID>
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: <YOUR-CLIENT-ID>
            client-secret: <YOUR-CLIENT-SECRET>
        provider:
          twitch:
            # ref: https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#client-credentials-grant-flow
            token-uri: https://id.twitch.tv/oauth2/token

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/twitch?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: <YOUR-MYSQL-ROOT-PASSWORD>
#  sql:
#    init:
#      mode: always
#      schema-locations: "sql/database-init.sql"

  cache:
    caffeine:
      spec: expireAfterWrite=1m

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # incoming HTTP requests
    com.twitchplus.backend.external.TwitchApiClient: DEBUG
    org.springframework.jdbc.core: DEBUG  # SQL
